export default {
	result: [],
	nbPage: 0,
	allgare: [],
	nameGare:[],
	horaireGare:[],
	allhorairegare:[],
	datafrequentation:[],
	departementmap:[],
	nationalfrequentation:[],
	queryList:[],
	queryMap: new Map(),
	numpage: 1,
	currentGare: [],
	currentGarename : String,
	uicgare : String,
	currentdepartementGare : String,
	mapMarker: [],
	etatPage: 0,
	indexPage: 0,
	historiqueGare: [],
	namedepartement: [],
	namecommune: [],
	filter: "Name",
	objettrouve: [],
	pageObjettrouve: 1,
	objetCurrentPage: [],
	liste_code:[],
	statsnumber:[],
	statslabels:[],

}